# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: Build
    displayName: 'Build demo-app'
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'acr'
            repository: 'demo-app'
            command: 'buildAndPush'
            Dockerfile: 'src/Dockerfile'
            buildContext: 'src/.'
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: 'k8s'
            artifact: 'manifest'
            publishLocation: 'pipeline'