apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dumpster-live-dep
  labels:
    workshop: "true"
    app: dumpster-01
spec:
  replicas: 3
  selector:
    matchLabels:
      workshop: "true"
      app: dumpster-01
  template:
    metadata:
      name: dumpster-live-pod
      labels:
        workshop: "true"
        app: dumpster-01
    spec:
      containers:
      - name: dumpster-live-pod-container
        image: poznajkubernetes/pkad
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready11
            port: 8080
          periodSeconds: 5
          initialDelaySeconds: 15
        ports:
        - containerPort: 8080
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dumpster-live-svc
  labels:
    workshop: "true"
    app: dumpster-01
spec:
  type: NodePort
  selector:
    app: dumpster-01
    workshop: "true"
  ports:
  - name: http
    port: 80
    targetPort: 8080
